version: "3.7"
services:
  api:
    build:
      context: ./api
    ports:
      - 80:80
    volumes:
      - ../folio-scraping-api:/opt/api:cached
  front:
    build:
      context: ./front
    ports:
      - 3000:3000
    volumes:
      - ../folio-scraping-front:/opt/front:cached